services:
  apirestsupermarket: #nombre de la app establecido en application.properties
    build: ApiRest_SuperMarket
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://supermarket:3306/supermarket?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 123456
      DB_PLATFORM: org.hibernate.dialect.MySQLDialect
    restart: always
    depends_on:
      supermarket:
          condition: service_healthy
  supermarket: #configuraciones de base de datos dockerizada
    image: mysql:8.4 #misma versión que esté en el pom
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: supermarket
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10